version: "3.7"

services:

  db:
    image: postgres:10.7-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-test}
      POSTGRES_USER: ${POSTGRES_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

volumes:
  postgres_data:
